---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jimsgarage # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: jimsgarage-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.l0t.us" # change to your domain
  dnsNames:
    - "*.l0t.us" # change to your domain
    - l0t.us # change to your domain
